### ISSUE TITLE
Reduce test/development dependencies.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/culture#29]
During the lead-up to `0.17.0` across the main gems, several new test/development dependencies came in, but they are not necessarily needed.

---

**UPDATE:** Inclusion of `nenv` and `dotenv` is deep in the test suite, but `rspec-logsplit` was removed.

**Comment by PikachuEXE** [comment]
I am seeing `rspec-logsplit` in runtime dependencies
https://rubygems.org/gems/celluloid/versions/0.17.1.2

Any reason for that?

**Comment by digitalextremist** [comment]
Yes, it handles run logs not just test logs. But it's not being deployed by default.

**Comment by tarcieri** [comment]
The stdlib `Logger` supports rotation FWIW (see `split_age`)

**Comment by digitalextremist** [comment]
That's good to know. 

Actually I misspoke though. It's not rotating, it's grouping log output by spec file and delineating block output within that file, referencing the outputting block. Still worth removing and only using that functionality if the gem is installed.

**Comment by morgoth** [comment]
Probably `bundler` as well shouldn't be part of runtime requirment

**Comment by gaffneyc** [comment]
Unless bundler is actually required (as in `require "bundler"`) by any of the gems themselves it should be removed as a dependency entirely.

**Comment by digitalextremist** [comment]
This was resolved in #33
