### ISSUE TITLE
Unified gem linkage strategy. 

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/culture#6]
All these gems having dependencies on each other has for now forced `gemspec` inclusion versus `Gemfile` listings that allow a remote repository to be used rather than having to cut fractional gems.

There has to be a way to blend both and stop needing to push to `rubygems` just to test on CI or provide testable updated code to other gems.

**Comment by digitalextremist** [comment]
Discussion in bundler/bundler#3594
And on [StackOverflow](http://stackoverflow.com/questions/29893470/how-to-create-interdependent-ruby-gems-with-bundler-and-still-use-repositories)

**Comment by digitalextremist** [comment]
For now this was solved by the semi-ugly but working ( right now ) approach of introducing another gem which purely exists to depend on:

- `celluloid-supervision`
- `celluloid-pool`
- `celluloid-fsm`
- `celluloid-extras`

That's `celluloid-gems` ( very original name, I know )

Then there's `celluloid-essentials` which now *only* depends on `celluloid-gems` and `celluloid` which only depends on `celluloid-essentials` ... what made this all work, is that all the gems inside `celluloid-gems` now individually depend on `celluloid` ... which I guess means circular dependencies *of a certain kind* don't work, which is probably the kind that are not separated by an intermediate dependency.

About to verify all this completely.

**Comment by digitalextremist** [comment]
The new problem ( @niamster? ) is although there are no circular dependencies reported, all the dependencies don't download. If you run `bundle update` on `celluloid` for example, it only goes two levels deep and grabs `celluloid-gems` and `celluloid-essentials` but *not* the dependencies of `celluloid-gems` ...

**Comment by niamster** [comment]
I'm afraid that this way you won't be able to override the celluloid-xxx in the Gemfile of the dependent gem.

**Comment by digitalextremist** [comment]
I can override the sources, but they don't link into the bundle at all.

**Comment by digitalextremist** [comment]
Another issue posted, with diagram: bundler/bundler#3597

**Comment by niamster** [comment]
I've checked bundler code and it's not possible right now. It doesn't flatter the dependencies properly.

**Comment by digitalextremist** [comment]
What gem arrangement can we make that's compatible? Is it level/tier/layer limited, or?

**Comment by digitalextremist** [comment]
I removed `celluloid-gems` and made `celluloid-essentials` a peer of the gray four, and had celluloid depend on those five, and now `celluloid` is building properly and running its tests.

Now trying the individual 5 gems.

**Comment by digitalextremist** [comment]
Only when I include *every gem* on every other gem, does it seem possible.

**Comment by digitalextremist** [comment]
Yep. That's what it takes for `celluloid-supervision to resolve. Duplicating for all others. So it's a return to the same problem before, but at least now I've solved depending on a repository.

fml

**Comment by digitalextremist** [comment]
@niamster do you think you could write a little script we can put into `culture/gemspec` that allows us to put one line in each `Gemfile`, and one line in each `gemspec`, where requires all the gems which *this gem* is not? Changing all these files repeatedly for versions and such is extremely problematic.

**Comment by niamster** [comment]
@digitalextremist I'll do this tonight after work

**Comment by digitalextremist** [comment]
Awesome. Thanks very much @niamster!

**Comment by digitalextremist** [comment]
This was solved for now, in #10 and #12.

@bundler/owners we wrote an addon to sync our many `Gemfile` and `gemspec` pairs rather than try to resolve the circular dependency issue right now.
